## Playbook to complete my standard LAMP stack build on a CentOS 6.x server.
## Assumes you have a minimal install in place already plus ansible installed
- name: "Initialize the current host as a LAMP server"
  hosts: all
  gather_facts: False
  sudo: yes
  vars:
    ansible_python_interpreter: "/usr/bin/env python"

  tasks:
    ## Base setup
    - name: "Install extra yum repos"
      yum: name={{ item }} state=present
      with_items:
        - https://dl.iuscommunity.org/pub/ius/stable/CentOS/6/x86_64/ius-release-1.0-14.ius.centos6.noarch.rpm
        - http://www.percona.com/downloads/percona-release/redhat/0.1-3/percona-release-0.1-3.noarch.rpm
    
    - name: "Install base packages"
      yum: name={{ item }} state=present
      with_items:
        - gcc
        - gcc-c++
        - git
        - bind-utils
        - telnet
        - wget
        - unzip
        - strace
        - MySQL-python
        - rsync
    
    ## MySQL (Percona) setup
    - name: "Install MySQL Bits"
      yum: name={{ item }} state=latest
      with_items:
        - Percona-Server-client-56
        - Percona-Server-server-56
        - Percona-Server-devel-56
      notify: enable mysql

    ## HTTPD setup
    - name: "Install HTTPD Bits"
      yum: name={{ item }} state=latest
      with_items:
        - httpd
        - httpd-devel
        - httpd-tools
      notify: enable httpd

    ## PHP Setup
    - name: "Install PHP Bits"
      yum: name={{ item }} state=latest
      with_items:
        - php56u
        - php56u-cli
        - php56u-common
        - php56u-devel
        - php56u-gd
        - php56u-gmp
        - php56u-mbstring
        - php56u-mcrypt
        - php56u-mysqlnd
        - php56u-opcache
        - php56u-pdo
        - php56u-pear
        - php56u-pecl-igbinary
        - php56u-pecl-jsonc
        - php56u-pecl-jsonc-devel
        - php56u-pecl-redis
        - php56u-process
        - php56u-xml

  ## Handlers
  handlers:
    - name: enable mysql
      service: name=mysql enabled=yes

    - name: enable httpd
      service: name=httpd enabled=yes
